### ISSUE TITLE
dcovU_stats not working as expected

### ISSUE THREAD

**Issue by vnmabus** [mariarizzo/energy#1]
The vector returned from dcovU_stats has incorrect results. An example is in the following code:

```
> f = t(matrix(c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16), nrow=4))

> dcovU(f,f)
42.66667 

> dcovU_stats(f,f)
   dCovU   bcdcor   dVarXU   dVarYU 
240.3333   1.0000 240.3333 240.3333 
```
As can be seen, the values in dcovU_stats do not match the result from dcovU, which is the correct result.

**Comment by mariarizzo** [comment]
It works correctly. The arguments to dcovU_stats must be distance matrices (see manual). This is just a utility function.
> f = t(matrix(c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16), nrow=4))
> 
> dcovU(f, f)
   dCovU 
42.66667 
> Dx <- as.matrix(dist(f))
> dcovU_stats(Dx, Dx)
   dCovU   bcdcor   dVarXU   dVarYU 
42.66667  1.00000 42.66667 42.66667
