### ISSUE TITLE
Normalisation of E-statistic

### ISSUE THREAD

**Issue by NikTheGeek1** [mariarizzo/energy#3]
Hi guys, 

This is actually not an issue with the package, more like an issue _I am_ having when using your package. I am trying to normalise the e-statistic using your suggestion in  Energy distance (2016; pg3) but keep failing. In your article, it's written that one of the ways to normalise the statistic is to divide by an estimate of _2E||X-Y||_. It should be straightforward but I can't figure it out. Also in your article, you are using as an example the _iris_ dataframe: `eqdist.etest(iris[1:100, 1], c(50, 50), R = 999)` where you get `E-statistic = 123.5538`. 
It would be terribly helpful if you could send me how you would normalise this result in R.

Thanks
Nikos

**Comment by mariarizzo** [comment]
Nikos,

An estimate of $2E||X-Y||$ is 2A from page 28:
$$
A = \frac{1}{nm} \sum_{i=1}^n \sum_{j=1}^m  \| x_i – y_j \|.
$$

Divide $\mathcal E_{n,m}$ (not T) by 2A.  The statistic $\mathcal E_{n, m}$ estimates the numerator in H. The statistic T is the V-statistic for the test.

In this example, you could write a loop, or use outer(), or subset the distance matrix to get A:

dst <- as.matrix(dist(iris[1:100, 1:4]))
> xydst <- dst[51:100, 1:50]
> mean(xydst)
[1] 3.301223

Regards,

    Maria

**Comment by NikTheGeek1** [comment]
Thanks for the prompt reply. 

So if I am getting it right, calculating B and C in the same way (as in page 28):
$$
B = \frac{1}{nn} \sum_{i=1}^n \sum_{j=1}^n  \| x_i – y_j \|.
$$
$$
C = \frac{1}{mm} \sum_{i=1}^m \sum_{j=1}^m  \| x_i – y_j \|.
$$
then 
$(2A-B-C) / (2A) =  0.7485335$, which is the normalised e-statistic, right? 

It makes sense, thanks
Nikos

**Comment by mariarizzo** [comment]
Nikos,

Yes, that is correct. Alternately you could get the numerator by dividing T by the coefficient (nm)/(m+n) (=50 in this case).

Maria Rizzo, Professor
Department of Mathematics & Statistics
Bowling Green State University
