### ISSUE TITLE
Odd results of `pdcor.test` when one input is a vector of repeated values, e.g. `rep(3.14, 100)`

### ISSUE THREAD

**Issue by CameronBieganek** [mariarizzo/energy#5]
When I provide three independent vectors to `pdcor.test`, I get `pdcor ≈ 0` and a non-significant p-value, like this:

```r
> pdcor.test(rnorm(100), rnorm(100), rnorm(100), R = 199)

	pdcor test

data:  replicates 199
pdcor = -0.011295, p-value = 0.47
sample estimates:
      pdcor 
-0.01129471 
```

However, if one of the vectors only contains one unique value, then I get `pdcor = 0` and a significant p-value (0.005), like this:

```r
> pdcor.test(rep(1.2, 100), rnorm(100), rnorm(100), R = 199)

	pdcor test

data:  replicates 199
pdcor = 0, p-value = 0.005
sample estimates:
pdcor 
    0
```

I can't say I have a very good understanding of the theory behind (partial) distance covariance/correlation, so I'm not sure what exactly the expected behavior is. And I realize my example is somewhat pathological (see below for how I encountered this scenario). If pdcor is truly zero, then I would expect a non-significant p-value. Is this the expected behavior? If not, is there a way to make `pdcor.test` more robust to this edge case?

Whether intentional or not, `dcor.test` seems to avoid this problem by returning an `NA` for the p-value:

```r
> dcor.test(rep(1.2, 100), rnorm(100), R = 199)

	dCor independence test (permutation test)

data:  index 1, replicates 199
dCor = 0, p-value = NA
sample estimates:
     dCov      dCor   dVar(X)   dVar(Y) 
0.0000000 0.0000000 0.0000000 0.5809601 
```

The reason this arises in practice is because I have some simulated data sets with 5,000 samples where all variables are count variables. In some experiments that I am running, I take an N=100 subset of the data, which can result in some columns being all zero.

**Comment by mariarizzo** [comment]
Look at the operation of double centering, which is part of the definition of the sample coefficient pdcor. 
dcor does not use double centering. 
Possibly add logic around the call to return dcor when this happens.

**Comment by mariarizzo** [comment]
See energy version 1.7-9 released 2022-01-25 for the update to pdcor.test to handle this case.
