### ISSUE TITLE
Fatal Error using pdcor.test

### ISSUE THREAD

**Issue by zxs132** [mariarizzo/energy#7]
Hello, I am a researcher in South Korea using partial correlation to analyze mental health data.

I am encountering a problem while utilizing pdcor.test.

I am running the test to find partial distance correlation between two vectors, given another vector.

The length of two vectors are around 2000, and the given vector's length varies from 2000 to 40000.

Also, I am trying to fun pdcor.test with 100 replications within nested loop of 25 by 25.

Then, I am keep getting a fatal error.

Can you suggest me a solution?

**Comment by mariarizzo** [comment]
To compute a partial distance correlation pdcor(x, y, z) the variables x, y, and z must be triples; that is, all of them must have the same number of rows. In the formula, dcor must be defined for (x,y), (x,z), and (y,z). The last two will fail in your example, so pdcor is undefined and it is correct for pdcor to return an error and pdcor.test fails, too. In fact, no measure of association is meaningful for unpaired data. I believe partial correlation would also fail; there is a package ppcor with function pcor if you want to try.
