### ISSUE TITLE
Add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [mariarizzo/energy#8]
I suggest adding the topics `r-package`, `statistics`, `multivariate-analysis` in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by mariarizzo** [comment]
Thank you for the suggestions.

Maria Rizzo, Professor
Department of Mathematics & Statistics
Bowling Green State University
***@***.***



On Aug 24, 2024, at 9:09 AM, Beliavsky ***@***.***> wrote:



I suggest adding the topics r-package, statistics, multivariate-analysis in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics
