### ISSUE TITLE
Consider adding weighted version of statistics

### ISSUE THREAD

**Issue by ngreifer** [mariarizzo/energy#9]
[Huling & Mak (2024)](https://doi.org/10.1515/jci-2022-0029) provide the weighted energy distance and [Huling, Greifer, & Chen (2023)](https://doi.org/10.1080/01621459.2023.2213485) provide the weighted distance covariance. Although they do not describe tests using the weighted versions of the statistics, it might still be useful to include calculations of the weighted statistics in the package. Thanks for considering!

**Comment by mariarizzo** [comment]
Thank you for the suggestion. The R package independenceWeights on CRAN seems to cover the main application.
